### ISSUE TITLE
Not able to use custom messages in hardware_arduino

### ISSUE THREAD

**Issue by ksakash** [AUV-IITK/Anahita#25]
The `arduino_node.cpp` uses two custom-made messages included from the package `hyperion_msgs`. There are problems including the header files generated due to `Depth.msg` & `Pressure.msg`. @Mayankm96 can you look into this, as I don't have much experience with **Arduino CMake**

**Comment by Mayankm96** [comment]
As far as I remember, I did add those statements. 

According to the [link](http://wiki.ros.org/rosserial_arduino/Tutorials/Adding%20Custom%20Messages), to add custom messages for Arduino you need to add them first to the ROS library which arduino refers to and build them there.  Only then the arduino node can use them. However, this reduces the portability of the code.

However, for linking through CMake it is another story. I'll have to check again but it wasn't working as well at the time I wrote the code. The easiest solution that I can think of to use standard messages in arduino cpp node and then have another node which converts them into our custom messages. 

I shall also add that when using sensor messages, it is advised to have `Header` so that's why I believe using those custom messages are a good practice. I'll keep you updated if I find a better solution to this issue.

**Comment by 7ayushgupta** [comment]
@Mayankm96 any updates on this?
